[package]
name = "indexer"
version = "0.1.0"
authors = ["Aurel <aurelien.catinon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
types = { path = "../types" }

eth2 = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
lighthouse_types = { git = "https://github.com/sigp/lighthouse", package = "types", branch = "stable" }
sensitive_url = { git = "https://github.com/sigp/lighthouse", branch = "stable" }