[package]
name = "shared"
version = "0.1.0"
authors = ["Aurélien <aurelien.catinon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
slot_clock = { git = "https://github.com/sigp/lighthouse", branch = "stable" }